# Generated by Django 3.2 on 2022-08-16 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=100)),
                ('head_of_department', models.CharField(max_length=60)),
                ('tutor', models.CharField(max_length=50)),
                ('college_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.college')),
            ],
        ),
    ]
