# Generated by Django 3.2 on 2022-08-16 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='head_of_department',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='department',
            name='tutor',
            field=models.CharField(max_length=100),
        ),
    ]
